# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockMarket' do
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.2.0'
end
